# Generated by Django 4.1.3 on 2022-12-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_patient_symptoms_alter_appointment_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Birthdate',
            field=models.DateField(default='', null=True),
        ),
    ]
