# Generated by Django 4.1.3 on 2022-12-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_alter_patient_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Birthdate',
            field=models.DateField(default='%d %B %Y', null=True),
        ),
    ]
