# Generated by Django 4.1.3 on 2022-12-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_alter_patient_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Birthdate',
        ),
    ]
